# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#DATABASE_USERNAME = postgres.smwblucderfnsgmgzenw
#DATABASE_PASSWORD =MACSMaatha123@


# HikariCP Connection Pool Settings (Prevents dropped connections)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.minimum-idle=2

# Server and JPA Configuration
server.port=${PORT:8080}
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=0
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

# Supabase S3 Storage Configuration
supabase.s3.endpoint=https://smwblucderfnsgmgzenw.storage.supabase.co/storage/v1/s3
supabase.s3.region=ap-southeast-1
supabase.s3.access-key=0e66b9386ba97ea085f0f5243118522b
supabase.s3.secret-key=0e696eac15ac6f7d648a9636083fa61e267bb3dac1a270357745128defba9331
supabase.s3.bucket=medical-records
supabase.avatars.bucket=${SUPABASE_AVATARS_BUCKET:avatars}
supabase.s3.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtd2JsdWNkZXJmbnNnbWd6ZW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1OTM0MzIsImV4cCI6MjA5NDE2OTQzMn0.Ioq4zTPt3iZstMc3Cd5n6HIj8LEWjpMqZn0FsoRM5PM

# Multipart File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
